Screen list/step№3
Andreeiich/StockApp pull request #1
Opened 2023-10-25 20:13 UTC by Andreeiich

Задача №6. Написать экран со списком популярных акций используя шаблон проекта и выложить PR. 

https://github.com/Andreeiich/StockApp/assets/78752247/cbe8a970-d4af-483a-8b7f-7a144c5cc275

2023-10-26 07:57 UTC, LuckyDmitry requested changes

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/data/DataRepositoryImpl.kt
> +    override suspend fun getAllDataOfStocks(stock: String): MutableList<StockDTO> {
Почему mutable? Просто list, уже тот, кто будет использовать решит, нужно модифицировать

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/DataDomain.kt
> +   val stockDTOList : MutableList<StockDTO>
List

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/DataRepository.kt
> +    suspend fun getAllDataOfStocks(stock:String): MutableList<StockDTO>
Отступы после stock:
После функции, посмотри kotlin code style и следуй ему 👍

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +class GetStockDataUsecase @Inject constructor(
UseCase

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +            if (i % 1000 == 0 && i != 0) {
Это что за логика? i какая-то непонятная, нужно описательные имена даже для таких переменных

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +        for (i in serverDataNameOfStocks.indices) {
Весь код переписать на map функцию, если у тебя появляется mutableList и ты добавляешь элементы в цикле, это хороший знак, что скорее всего ты данные из одного типа в другой переводишь, тогда используй map

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +        var currentCompanies: MutableList<String> = ArrayList()
currentCompanies не дает понимания, что это
Тогда уж filteredCompanies

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +        val serverDataNameOfStocks = repository.getAllNameOfStocks()
serverData избыточно, можно просто stockNames

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +
Этот код можно переписать на filter + map + toString

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainViewModel.kt
> +    fun setDataInStocksAdapter(data: DataUI, adapter: StockAdapter) {
DataUi не совсем понятно, какая именно data 
Если это относится к акции, давай так и указывать

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +                    .plus("%)")
Тут часть кода дублируется, давай совместим ее
Под if else лучше помещать код, который отличается. Который повторяется - выносить в одно место

2023-10-26 07:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +            val conditionColor =
ConsitionColor - не понял тоже, зачем переменная

2023-10-26 07:59 UTC, LuckyDmitry commented
Здорово придумал с каждой тысячной акцией и в остальном выглядит тоже отлично 👍

2023-10-26 16:29 UTC, ilsave commented on app/build.gradle
> +        debug{
пустая лямбда ) надо убрать )

2023-10-26 16:30 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/data/StockDTO.kt
> +data class StockDTO(
все должно быть val

2023-10-26 16:30 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/data/StockNameDTO.kt
> +data class StockNameDTO(
отступы

2023-10-27 10:49 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/data/DataRepositoryImpl.kt
> +    override suspend fun getAllDataOfStocks(stock: String): MutableList<StockDTO> {
Ошибся скорее всего. Поправил.

2023-10-27 13:58 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUsecase.kt
> +            if (i % 1000 == 0 && i != 0) {
Это логика, чтобы в запрос отправлять по 1000 наименований акций, чтобы минимизировать время запросов. По 1000 имен, сервер API обрабатывает за запрос нормально. Для прогрузки 11300+ акций нужно примерно 14 секунд. Но это пока временное решение. Переменную i исправил, согласен, не совсем ясно за что отвечает.

2023-10-27 16:37 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +            val conditionColor =
conditionColor нужен, чтобы вычислить цвет на установку в контейнер акции  исходя из позиции контейнера в recyclerView и установить его в defaultColor данного контейнера.

2023-10-28 19:54 UTC, LuckyDmitry requested changes

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseСase.kt
> +        val currentData: MutableList<StockDTO> = ArrayList()
Предпочительней использовать сразу map
Mutable переменные плохая практика

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseСase.kt
> +        val stockNames = stockNamesAll.subList(0,10)
Что если меньше 10 элементов? 
Давай в констану это вынесем. Все числа такие лучше выносить в константы и давать осмысленные имена
Почитай про magic numbers

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseСase.kt
> +        val str: String = currentCompanies.toString().replace(" ", "")
str- плохое имя, почитай про то, как называть переменные. Плохие и хорошие практики

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseСase.kt
> +        currentData.addAll(repository.getAllDataOfStocks(str.substring(1,str.length-1)))
Что если строка пустая?

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/StockDataHelperImpl.kt
> +        stockDTOList: MutableList<StockDTO>
Никаких mutablelist
Все что mutable не безопасно, это только в крайних случаях использовать

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainViewModel.kt
> +    fun getData() {
Зачем два метода? Может один оставим?

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +            val signValuta = if (stock.changes >= 0) "+$" else "-$"
Valuta? Лучше использовать полностью английские слова

2023-10-28 19:54 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +            colorStock.setTint(ContextCompat.getColor(popularStock.context, colorStockPosition))
stockColor

2023-10-29 17:36 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/StockDataHelperImpl.kt
> +        stockDTOList: MutableList<StockDTO>
Виноват ,исправил.

2023-10-29 17:41 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainViewModel.kt
> +    fun getData() {
ок, оставил один.

2023-10-29 21:03 UTC, ilsave commented on app/build.gradle
>  }
тут и везде ниже надо бы добавить по пустой строчке, чтобы не было знаков стоп)

2023-10-29 21:04 UTC, ilsave commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginStart="16dp"
в dimes

2023-10-29 21:04 UTC, ilsave commented on app/src/main/res/layout/popular_stocks.xml
> +            android:layout_marginStart="8dp"
все dp надо вынести в файл

2023-10-30 14:09 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseСase.kt
> +        currentData.addAll(repository.getAllDataOfStocks(str.substring(1,str.length-1)))
Сделал.

2023-11-01 11:45 UTC, LuckyDmitry approved these changes

2023-11-01 11:45 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +    private var serverDataStock: List<StockDTO> = ArrayList()
Зачем локально храним список?

2023-11-01 11:45 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val stockNames = stockNamesAll.subList(LIST_START, LIST_END)
Если от пустого списка вызвать этот метод, все будет ок?

2023-11-01 11:45 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val currentCompanies = stockNames.map { it.companyName }
companyNames скорее

2023-11-01 11:45 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val result: DataDomain = if (nameOfCompanies.isEmpty()) {
Можно проще, если список пустой - возвращаем пустой массив. И не нужно хранить локальную копию массива

2023-11-01 11:56 UTC, ilsave commented on app/src/main/res/drawable/close.xml
> +    <!--Ругается на эти поля при сборке проекта,оставил-->
давай тогда удалим эти строчки, ни к чему тут лишний код

2023-11-01 11:56 UTC, ilsave commented on app/src/main/res/drawable/edit_text_style.xml
> +</shape>
тут пустая строчка

2023-11-01 11:57 UTC, ilsave commented on app/src/main/res/drawable/round_style.xml
> +</shape>
и тут )

2023-11-01 11:57 UTC, ilsave commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="24dp"
давай вынесем в dimens

2023-11-01 11:57 UTC, ilsave commented on app/src/main/res/layout/popular_stocks.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
пустая строчка )

2023-11-01 11:58 UTC, ilsave commented on app/src/main/res/values/dimens.xml
> +
и тут строчка)

2023-11-01 11:58 UTC, ilsave commented on app/src/main/res/values/themes.xml
> +
строчка

2023-11-01 13:58 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +    private var serverDataStock: List<StockDTO> = ArrayList()
Исправил, не подумал об этом.

2023-11-01 14:10 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val stockNames = stockNamesAll.subList(LIST_START, LIST_END)
Добавил проверку и протестировал.

2023-11-01 14:35 UTC, Andreeiich commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="24dp"
Ага, пропустил)

2023-11-01 17:42 UTC, ilsave commented
Approved

2023-11-01 17:54 UTC, Oleg-root commented on app/src/main/java/com/example/stockapp/core/domain/CoroutinesUseCase.kt
>  }
newline в конце файла чтоб красного значка не было

2023-11-01 19:11 UTC, Oleg-root requested changes
ПР хороший, Андрей крут, комменты оставил

2023-11-01 19:11 UTC, Oleg-root commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +        @SuppressLint("ResourceAsColor")
SuppressLint? А зачем? Не вижу в коде захардкоженных методов, которые принимают фактически RGB. Убери SuppressLint

2023-11-02 13:46 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/data/ServerDataApi.kt
> +    ): MutableList<StockDTO>
Исправил)) Не везде подчистил)

2023-11-02 13:47 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        }
Все ок, во viewModel обрабатываем эту ситуацию)

2023-11-02 13:50 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +        @SuppressLint("ResourceAsColor")
убрал

2023-11-02 16:38 UTC, Oleg-root approved these changes
аппрув

2023-11-02 18:46 UTC, merged