Search stocks/task 7
Andreeiich/StockApp pull request #2
Opened 2023-11-04 19:24 UTC by Andreeiich

Добавил поиск, и оформление  строки поиска при действии.

https://github.com/Andreeiich/StockApp/assets/78752247/43f60766-8b36-4488-88d5-d83263bf202b

2023-11-05 00:04 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/domain/GetSearchStockDataUseCase.kt
> +    override suspend fun invoke(params: String): StockData? {
Введи плиз в курс дела. Расскажи кратко о назначении этого класса и идее, которая стоит за интерфейсом CoroutinesUseCase

2023-11-05 00:10 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/domain/GetSearchStockDataUseCase.kt
> +            repository.getAllDataOfStocks(nameOfCompanies.substring(1, nameOfCompanies.length - 1))
Можешь на примере кратко рассказать про преобразования в этом методе.
Вот ты получаешь `params`, что там например хранится?
Дальше, что в `searchData`, `companyName`, `nameOfCompanies`
И вот этот маневр тоже интересный: `nameOfCompanies.substring(1, nameOfCompanies.length - 1)`

2023-11-05 00:42 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/domain/GetSearchStockDataUseCase.kt
> +        return result.toUI()
Я заметил некоторое условное деление на модули по clean architecture. Вижу у тебя в data 'модуле' определена сущность StockDTO. Там ты ее добываешь и сквозь domain она путешествует до самого presentation слоя. То есть presentation слой зависит на data. Это не совсем правильно, потому что для ретрофита (data) у нас одна модель, для бизнеса (domain) она должна быть другая, а для presentation вообще другая (даже, если одинаковые и маппинг апсолютно прямой) иначе, в этой или подобной ситуации, когда ты будешь прикручивать модуляризацию к проекту, ты увидишь, что domain и presentation слои требуют подключить ретрофит, хотя он к ним не относится. Это одна из причин, почему сквозные зависимости. Еще это будет мешать инкрементальной сборке. 
На собеседовании можешь прям так и ответить, если спросят про модуляризацию и CA.
Предлагаю сейчас поправить этот момент, если мы примеряем Клин Аркитектуре , - ну как минимум убрать зависимость presentation на data

2023-11-05 00:44 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val currentData = repository.getAllDataOfStocks(
С дубированием мы можем что-то придумать?

2023-11-05 00:48 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +                    this@MainActivity, getString(R.string.Stocks_unloaded), Toast.LENGTH_LONG
Отличная мысль!

2023-11-05 00:56 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockAdapter.kt
> +    lateinit var startedData: StockData
Много где пропущены модификаторы доступа вообще. А здесь, хоть поле и не private, все равно придуман метод setStartingData

2023-11-05 15:14 UTC, LuckyDmitry approved these changes

2023-11-05 15:18 UTC, McAndyLarkin requested changes
Надо обсудить пару моментов

2023-11-06 10:48 UTC, Oleg-root requested changes

2023-11-06 14:41 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetSearchStockDataUseCase.kt
> +    override suspend fun invoke(params: String): StockData? {
Данный класс служит для принятия данных с UI для поиска, и передачи этих данных методам в слой data, а так же чтобы получить данные из слоя data, обработать их и передать на слой UI.

2023-11-06 14:48 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetSearchStockDataUseCase.kt
> +            repository.getAllDataOfStocks(nameOfCompanies.substring(1, nameOfCompanies.length - 1))
В params хранятся символы которые вводит user  в строке поиска на макете, это строка. searchData это данные из сети, представляет собой объект класса List<StockNameDTO>. companyName - это List<String>, получаем названия всех компаний по которым в дальнейшем будем делать запрос. nameOfCompanies - это уже строка, которая хранит только имена, исключает пробелы. А последний маневр нужен для того, чтобы исключить "[" и "]" в начале и в конце строки.

2023-11-06 15:03 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val currentData = repository.getAllDataOfStocks(
Я не заметил там дублирования. Подскажи, где именно дублирую.

2023-11-06 17:37 UTC, Andreeiich commented on app/src/main/res/layout/activity_main.xml
>              android:textSize="@dimen/text_input_inner_text_size" />
Поправил. Спасибо, я не заметил, что шире.

2023-11-07 10:11 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/domain/GetStockDataUseCase.kt
> +        val currentData = repository.getAllDataOfStocks(
Этот класс и класс GetSearchStockDataUseCase.
Посмотри может там можно что-то придумать, чтобы избавиться от дублирования

2023-11-09 14:27 UTC, McAndyLarkin commented on gradle.properties
Файл  gradle.properties нужно класть в пиар, если что
Просто ключ должен быть в каком-то другом месте

2023-11-09 14:36 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
>                          viewModel.setDataInStocksAdapter(data, adapter)
Тут тоже надо убрать адаптер из вью модели

2023-11-09 21:10 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockViewModel.kt
> +    private val _state = MutableStateFlow<MutableList<StockData>?>(null)
Думаю, тут нужен List
Вью модель выдает его наружу не чтобы кто-то его снаружи менял

2023-11-09 21:15 UTC, McAndyLarkin commented on app/src/main/java/com/example/stockapp/features/home/presentation/StockViewModel.kt
> +    lateinit var stockAdapter: StockAdapter
Теперь чтоб уж совсем идеально было, сделай тоже самое с этим адаптером, оставь его в активити, из активити сделай подписку, а здесь чисто реализуй флоу
Пусть активити знает про вью модель и про адаптер, а они не знат ни про что
Как раз недавно объяснял Олегу и рисовал вот такую схемку 
![image](https://github.com/Andreeiich/StockApp/assets/51488300/28824ff3-aa8c-45e7-8567-ae2e19f60501)

2023-11-16 03:51 UTC, McAndyLarkin approved these changes

2023-11-16 14:40 UTC, merged