[support_of_request/task_8]: add customView for search stocks, add te…
Andreeiich/StockApp pull request #3
Opened 2023-12-10 13:31 UTC by Andreeiich

- Сделал customView для строки поиска.
- Добавил популярные запросы и запросы пользователя, которые меняют последний элемент по времени поиска.
- Добавил слушатель выбора акций из списка популярных и последних запросов пользователя. 

https://github.com/Andreeiich/StockApp/assets/78752247/4fd4ab42-13fc-4173-979c-f9265fa47ace

2023-12-10 19:33 UTC, AlexandrRumyantsev commented
В задании написано удалять последний по времени элемент из поиска и заменять новым, предполагаю, что имелось ввиду удалять самый старый, то есть первый элемент массива, а на видео заменяется 6-ой.
Также сниппеты предыдущих запросов должны заполняться слева направо, сверху вниз, левая граница первого элемента должна быть привязана к левой границе TextView, который принадлежит этой CustomViewGroup.

2023-12-10 19:39 UTC, AlexandrRumyantsev commented on app/src/main/res/layout/activity_main.xml
> +      <TextView
123

2023-12-10 19:52 UTC, AlexandrRumyantsev commented on app/src/main/res/layout/activity_main.xml
> +    </com.example.stockapp.features.home.presentation.SearchCustomView>
Как я понял, CustomViewGroup это наш переиспользуемый компонент и TextView должна быть частью этого компонента, потому что заголовок есть и у Recent Search и у Popular search, а, как я вижу, в xml файле TextView для каждого из двух CustomViewGroup добавляется отдельно.
![image](https://github.com/Andreeiich/StockApp/assets/46137399/2c3fe5d1-9d83-47fc-a5e6-358668f5d587)

2023-12-10 20:02 UTC, Oleg-root reviewed
Кастом вью от viewGroup это сильно, молодец

2023-12-10 20:02 UTC, Oleg-root commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="8dp"
в ресурсы

2023-12-10 20:02 UTC, Oleg-root commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_marginTop="8dp"
в ресурсы

2023-12-10 20:02 UTC, Oleg-root commented on app/src/main/res/layout/search_stock.xml
> +        android:padding="10dp"
в ресурсы и чуть ниже размер текста тоже туда

2023-12-10 20:16 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        }
Не понял сути, мы мапим один дата класс с одним полем String в другой дата класс с одним полем String

2023-12-10 20:19 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    }
Можно возвращать просто List, мы же не собираемся потом изменять его.

2023-12-10 20:25 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/stockapp/features/home/presentation/CustomViewListener.kt
> +
Неверный нэйминг, функция интерфейса абстрактна и не всегда будет выполнять "transferInfo", это будет зависеть от того, какая будет реализация, по идее она должна называть onClick или onItemClick

2023-12-10 20:32 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/stockapp/features/home/presentation/SearchCustomView.kt
> +
Можно сделать приватным и добавить сеттер, в который и будем передавать нужный листенер.

2023-12-10 20:39 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
Зачем мы второй раз записываем в searchCustomPopularRequests = findViewById<SearchCustomView>(R.id.SearchCustomPopularRequests), уже есть ссылка на этот объект, в строке 48, аналогично и для searchCustomSearched, ссылка уже получена в строке 46. И зачем нам вообще findViewById, если у нас подключен binding?

2023-12-10 20:43 UTC, AlexandrRumyantsev commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
> Это твои ресурсы. Ресурсы стоит хранить в "res", в данном случае можно положить в strings.xml

Тоже об этом подумал, но, по идее, популярные запросы - это как раз нечто, что мы должны получать из базы данных, если бы у приложения были пользователи, а значит хранить их в ресурсах не правильно, нужно хранить в каком то классе, как и делает Андрей.

2023-12-11 13:57 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    }
Всегда возвращать List
Не изменяемое лучше, чем изменяемое

2023-12-11 14:02 UTC, LuckyDmitry requested changes

2023-12-11 14:02 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/SearchCustomView.kt
> +        for (i in 0 until childCount) {
никаких i, лучше пиши сразу index

2023-12-11 14:02 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/presentation/SearchCustomView.kt
> +        var t: Int
Привести в порядок имена(имя меньше 3 символов не должно существовать)
Разбить большой метод на понятные функции

2023-12-11 20:10 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
Я оставлю так, как имитация некого запроса из БД.

2023-12-11 20:10 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    private var hadRequests = arrayListOf<String>("Nokia", "intel", "Visa", "AMD", "GM", "Nvidia")
Я оставлю так, как имитация некого запроса из БД.

2023-12-11 20:23 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +        popularStockListener.viewListener = this
Да, я поправил. Когда с пробросом с кастомной вьюхи возился, совсем и забыл, что работаю с binding. :)

2023-12-11 20:24 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
>                  binding.textInputInner.hint = ""
Чтобы не свитился во время ввода.

2023-12-11 21:01 UTC, Andreeiich commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.04"
Спасибо,Олег. Честно даже не заметил этого.

2023-12-12 03:47 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/domain/SearchDataHelperImpl.kt
> +class SearchDataHelperImpl:SearchDataHelper {
отступы

2023-12-12 03:48 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
можно оставить так, но лучше сделать через ресурсы, получится так, что ты возвращаешь лист интов (R.string.lyour_string, и так далее)

2023-12-12 03:49 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    private var hadRequests = arrayListOf<String>("Nokia", "intel", "Visa", "AMD", "GM", "Nvidia")
такая же тема

2023-12-12 03:49 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    /* set(value) {
зачем этот комментарий ?)

2023-12-12 03:50 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +                    searchJob?.cancel()// для отмены, если строка пустая стала, т.е. когда пользователь очистил строку ввода
комментарий выше строчки с кодом, а не на ней )

2023-12-12 03:51 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +            if (!searchCustomPopularRequests.children.any()) {//Проверка, чтобы не добавить повторно элементы, если пользователь вернется к поиску снова
такая же тема

2023-12-12 03:51 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +                    delay(400)
вынести в константы

2023-12-12 03:52 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +                        handler.post {
давай уберем хендлер и заменим его withcontext Main

2023-12-12 03:53 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +            val textView = layoutInflater.inflate(R.layout.search_stock, null)
а зачем каждый раз искать вьюшку ? можно вынести за пределы фора

2023-12-12 10:29 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
Ребят, хочу обратить ваше внимание на такой момент. По вашему совету, я перенес все строки в ресурсы. А как мне быть, когда пользователь делает запрос, и приходит строка?
![image](https://github.com/Andreeiich/StockApp/assets/78752247/6e743026-7eb0-4844-9b97-8bae528f92e1)

2023-12-12 10:30 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
Начинает ругаться метод, где я заменяю в этом массиве строку последнего запроса, так как она стринг, а массив уже параметризирован как Int.

2023-12-12 10:43 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
Ничего менять не буду, было много что сделано, а из-за этих ресурсов все летит к чертям. Кому надо, пусть делают.

2023-12-12 10:43 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    private var hadRequests = arrayListOf<String>("Nokia", "intel", "Visa", "AMD", "GM", "Nvidia")
Ничего менять не буду, было много что сделано, а из-за этих ресурсов все летит к чертям. Кому надо, пусть делают.

2023-12-12 10:44 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/CustomViewListener.kt
> +
У меня всегда будет выполнять transferInfo!

2023-12-12 11:15 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    /* set(value) {
удалил.

2023-12-12 11:16 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    /* set(value) {
Забыл удалить перед коммитом.

2023-12-12 15:37 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +                        handler.post {
Спасибо.

2023-12-12 15:46 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/presentation/MainActivity.kt
> +            val textView = layoutInflater.inflate(R.layout.search_stock, null)
Здесь приходится раздувать каждый раз разметку и искать на каждой textView, чтобы все это хозяйство расположить на customView. Если вынести за пределы фора, то будет IllegalStateException.

2023-12-14 07:33 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    private var hadRequests = arrayListOf<String>("Nokia", "intel", "Visa", "AMD", "GM", "Nvidia")
Переделал.

2023-12-14 07:33 UTC, Andreeiich commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        )
Переделал!

2023-12-18 17:04 UTC, LuckyDmitry commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        hadRequests.add(index, R.string.merc)
hadRequests.size вместо index, можно забыть эту переменную прибавить или удалить

2023-12-18 17:32 UTC, AlexandrRumyantsev approved these changes

2023-12-19 15:34 UTC, Oleg-root approved these changes

2023-12-19 20:43 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +    private val popularRequests
Давай уберем закоменченный код

2023-12-19 20:44 UTC, ilsave commented on app/src/main/java/com/example/stockapp/features/home/domain/UserSearchHistoryService.kt
> +        private var index = 0
Почему эти переменные в компанионе? Если это константы, то норм, если нет, то можно просто в класс вынести

2023-12-19 20:44 UTC, ilsave approved these changes
Поправить комменты и давайте вливать

2023-12-21 10:08 UTC, merged